description: >
  An executor preloaded with Rhino, Windows, and a number of useful dev tools

parameters:
  shell:
    default: powershell.exe -ExecutionPolicy Bypass
    description: 'The shell to use. Defaults to `powershell.exe -ExecutionPolicy Bypass`'
    type: string

machine:
  image: windows-server-2022
  resource_class: windows.<< parameters.size >>
  shell: << parameters.shell >>
